### PR TITLE
trivial commit

### PR DESCRIPTION
**Pull request by ablaom**

### CODE REVIEW

**Comment by ablaom** [comment]
The fail here looks like an issue OpenML end. 

@darenasc Can you clarify. 

I noticed I couldn't navigate to OpenML from my browser today because of some privacy something-or-other I had to override. Maybe related?


```
Error occurred : IOError(MbedTLS error code -9984: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed during request(https://www.openml.org/api/v1/json/data/61))
```

@giordano

**Comment by ablaom** [comment]
Indeed, if I try using OpenML from the current MLJBase I get the same error:

```julia
julia> using MLJBase
julia> OpenML.load(61)
Error occurred : IOError(MbedTLS error code -9984: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed during request(https://www.openml.org/api/v1/json/data/61))
```

**Comment by giordano** [comment]
> Maybe related?

I think so, it looks like they have some issues with their certificates

**Comment by ablaom** [comment]
https://github.com/openml/openml.org/issues/168

**Pull request merged**
