### PR TITLE
use ARFFFiles

### PR DESCRIPTION
**Pull request by jbrea**
Given that [ARFFFiles.jl is now clearly superior to my previous hack](https://github.com/cjdoris/ARFFFiles.jl/issues/4) I would prefer to use ARFFFiles.jl.

### CODE REVIEW

**Review by ablaom — APPROVED** [review]
Oh well, it certainly makes more sense to do this. Good job spotting that package and sorry about the extra work. 

I'm assuming this resolves all the old issues we closed before?

Since we are dropping the `parser` option we should make a new major release.

**Comment by jbrea** [comment]
Yes, no worries. The ARFFFiles developer did a great job in very short time :)

I went quickly through all the closed issues, and it looks all good (sorry for not writing good tests for now...).

In the last commit I put back in the `parser` option to allow for `parser = :auto` (`coerce(data, autotype(data))`).
But I dropped the `verbosity` and additional `kwargs` and `parser = :csv` does not return a CSV object anymore.
I guess we should therefore register version 2.0.0?

**Comment by ablaom** [comment]
Yeah, I've become pretty strict about tagging breaking releases as per semver . I got burnt too many times. 

Actually, I have another suggestion:  We make this branch the opening branch of a new repo - called OpenML.jl - and archive the current package until such time as we are actually doing MLJ-specific integration (uploading MLJ model runs, and so forth). This future "MLJOpenML" would be an extension of this new "OpenML" package. In this way users just interested in downloading datasets, and developers of other ML julia frameworks, can make use of the relatively light-weight framework-agnostic, "OpenML" as well.

Do you think this a good idea? Could you wait a few more days while we register the new pkg?

cc @darenasc

**Comment by ablaom** [comment]
Closing in favour of new repository: 

https://github.com/JuliaRegistries/General/pull/42436

**Pull request closed without merging**
